services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-pass-mais
    volumes:
      - pg_data:/bitnami/postgresql

  api:
    build:
      context: .
    container_name: api-pass-mais
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: api-pass-mais

volumes:
  pg_data:
